version: 2
jobs:
  build:
    docker:
      - image: circleci/php7.2.5-apache-node-browsers

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: rm -rf plugins
      - run: rm -rf artifacts
      - run: mkdir plugins
      - run: mkdir artifacts
      - run: wget -O php7.2.tar.gz https://jenkins.pmmp.io/job/PHP-7.2-Aggregate/lastSuccessfulBuild/artifact/PHP-7.2-Linux-x86_64.tar.gz --no-check-certificate
      - run: tar -xvf php7.2.tar.gz
      - run: wget https://github.com/pmmp/PocketMine-DevTools/archive/master.zip
      - run: unzip master.zip
      - run: cp -r PocketMine-DevTools-master/ plugins/
      - run: bin/php7/bin/php ci.php
      - run: cp -R plugins/DevTools/* $CIRCLE_ARTIFACTS
