version: 2
jobs:
  build:
    docker:
      - image: fedora:latest
    steps:
      - run:
          name: Tools install
          command: |
            yum update -y
            yum install -y git wget libnsl lsof
      - checkout
      - run:
          name: Git submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Download & install binary
          command: |
            wget https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz
            tar -xvf PHP_Linux-x86_64.tar.gz
      - run:
          name: Install DevTools
          command: |
            mkdir plugins
            bin/php7/bin/php -dphar.readonly=0 tests/plugins/PocketMine-DevTools/src/DevTools/ConsoleScript.php --make tests/plugins/PocketMine-DevTools --relative tests/plugins/PocketMine-DevTools --out plugins/DevTools.phar
      - run:
          name: Composer install
          command: bin/php7/bin/php bin/composer.phar install
      - run:
          name: Make server phar
          command: bin/php7/bin/php ci.php
      - store_artifacts:
          path: plugin_data/DevTools
          destination: Server phar
      - store_artifacts:
          path: plugins
          destination: DevTools