version: 2
jobs:
  build:
    docker:
      - image: fedora:latest

    steps:
      - checkout
      - run: yum install -y git wget unzip
      - run: git submodule sync
      - run: git submodule update --init
      - run: mkdir plugins
      - run: mkdir artifacts
      - run: wget https://jenkins.pmmp.io/job/PHP-7.2-Aggregate/lastSuccessfulBuild/artifact/PHP-7.2-Linux-x86_64.tar.gz
      - run: tar -xvf PHP-7.2-Linux-x86_64.tar.gz
      - run: wget https://github.com/pmmp/PocketMine-DevTools/archive/master.zip
      - run: unzip master.zip
      - run: cp -r PocketMine-DevTools-master plugins
      - run: bin/php7/bin/php ci.php
      - run: cp -R plugins/DevTools/* $CIRCLE_ARTIFACTS
